# Generated by Django 5.0.6 on 2024-07-09 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='author',
        ),
    ]
